lint:
  files_unchanged:
    - .github/workflows/linting.yml
    - .github/CONTRIBUTING.md
    - assets/multiqc_config.yaml
    - assets/nf-core-rnavar_logo_light.png
    - docs/images/nf-core-rnavar_logo_light.png
    - docs/images/nf-core-rnavar_logo_dark.png
